// Assignment Code
var generateBtn = document.querySelector("#generate");
var capLetters = ('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z');
var lowLetters = ('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');
var specCharacters = ('~','!','@','$','*');
function generatePassword() {
  console.log("Button appears to work")
  // 1 - prompt the user for the password criteria
  //  - password length, 8-128 characters. 
  //  - Whether or not to include uppercase, lower case, numeric, and/or special characters
  window.prompt("How many characters would you like your password? Between 8 - 128")
  
  window.prompt("Would you like to include capital letters?")
  window.prompt("Would you like to use lowercase characters?")
  window.prompt("Would you like to use special characters? ~, !, @, $, *")
  // 2 - validate input matches

  // 3 - generate pssword based on criteria

  // 4 - display password on page 
  return "generated password will go here";
}

// Write password to the #password input
function writePassword() {
  var password = generatePassword(); //Takes value generated by the "generatePasword" function
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
